package com.yuminsoft.cps.pic.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrivilege<M extends BasePrivilege<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setPaperstypeId(java.math.BigDecimal paperstypeId) {
		set("PAPERSTYPE_ID", paperstypeId);
	}

	public java.math.BigDecimal getPaperstypeId() {
		return get("PAPERSTYPE_ID");
	}

	public void setOperateAdd(java.math.BigDecimal operateAdd) {
		set("OPERATE_ADD", operateAdd);
	}

	public java.math.BigDecimal getOperateAdd() {
		return get("OPERATE_ADD");
	}

	public void setOperateMove(java.math.BigDecimal operateMove) {
		set("OPERATE_MOVE", operateMove);
	}

	public java.math.BigDecimal getOperateMove() {
		return get("OPERATE_MOVE");
	}

	public void setOperateRemove(java.math.BigDecimal operateRemove) {
		set("OPERATE_REMOVE", operateRemove);
	}

	public java.math.BigDecimal getOperateRemove() {
		return get("OPERATE_REMOVE");
	}

	public void setOperateDownload(java.math.BigDecimal operateDownload) {
		set("OPERATE_DOWNLOAD", operateDownload);
	}

	public java.math.BigDecimal getOperateDownload() {
		return get("OPERATE_DOWNLOAD");
	}

	public void setOperateRename(java.math.BigDecimal operateRename) {
		set("OPERATE_RENAME", operateRename);
	}

	public java.math.BigDecimal getOperateRename() {
		return get("OPERATE_RENAME");
	}

	public void setRoleId(java.math.BigDecimal roleId) {
		set("ROLE_ID", roleId);
	}

	public java.math.BigDecimal getRoleId() {
		return get("ROLE_ID");
	}

	public void setOperateWaste(java.math.BigDecimal operateWaste) {
		set("OPERATE_WASTE", operateWaste);
	}

	public java.math.BigDecimal getOperateWaste() {
		return get("OPERATE_WASTE");
	}

	public void setOperatePatchBolt(java.math.BigDecimal operatePatchBolt) {
		set("OPERATE_PATCH_BOLT", operatePatchBolt);
	}

	public java.math.BigDecimal getOperatePatchBolt() {
		return get("OPERATE_PATCH_BOLT");
	}
	
	public void setOperateDragSort(java.math.BigDecimal operateDragSort) {
		set("OPERATE_DRAGSORT", operateDragSort);
	}

	public java.math.BigDecimal getOperateDragSort() {
		return get("OPERATE_DRAGSORT");
	}
}
