package com.yuminsoft.cps.pic.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setNodeKey(java.lang.String nodeKey) {
		set("NODE_KEY", nodeKey);
	}

	public java.lang.String getNodeKey() {
		return get("NODE_KEY");
	}

	public void setNodeName(java.lang.String nodeName) {
		set("NODE_NAME", nodeName);
	}

	public java.lang.String getNodeName() {
		return get("NODE_NAME");
	}

}
