package com.yuminsoft.cps.pic.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFiletagPicture<M extends BaseFiletagPicture<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setPictureId(java.math.BigDecimal pictureId) {
		set("PICTURE_ID", pictureId);
	}

	public java.math.BigDecimal getPictureId() {
		return get("PICTURE_ID");
	}

	public void setFiletagId(java.math.BigDecimal filetagId) {
		set("FILETAG_ID", filetagId);
	}

	public java.math.BigDecimal getFiletagId() {
		return get("FILETAG_ID");
	}

}
