package com.yuminsoft.cps.pic.common.model.base;

import com.jfinal.plugin.activerecord.Model;

import oracle.sql.TIMESTAMP;

import java.sql.SQLException;
import java.sql.Timestamp;

import org.joda.time.DateTime;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePicture<M extends BasePicture<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setOrg(java.lang.String org) {
		set("ORG", org);
	}

	public java.lang.String getOrg() {
		return get("ORG");
	}

	public void setOenner(java.lang.String oenner) {
		set("OENNER", oenner);
	}

	public java.lang.String getOenner() {
		return get("OENNER");
	}

	public void setIdTpye(java.lang.String idTpye) {
		set("ID_TPYE", idTpye);
	}

	public java.lang.String getIdTpye() {
		return get("ID_TPYE");
	}

	public void setIdNo(java.lang.String idNo) {
		set("ID_NO", idNo);
	}

	public java.lang.String getIdNo() {
		return get("ID_NO");
	}

	public void setOutNo(java.lang.String outNo) {
		set("OUT_NO", outNo);
	}

	public java.lang.String getOutNo() {
		return get("OUT_NO");
	}

	public void setBranchid(java.lang.String branchid) {
		set("BRANCHID", branchid);
	}

	public java.lang.String getBranchid() {
		return get("BRANCHID");
	}

	public void setImgname(java.lang.String imgname) {
		set("IMGNAME", imgname);
	}

	public java.lang.String getImgname() {
		return get("IMGNAME");
	}

	public void setSavename(java.lang.String savename) {
		set("SAVENAME", savename);
	}

	public java.lang.String getSavename() {
		return get("SAVENAME");
	}

	public void setSortsid(java.math.BigDecimal sortsid) {
		set("SORTSID", sortsid);
	}

	public java.math.BigDecimal getSortsid() {
		return get("SORTSID");
	}

	public void setGeneeicSort(java.lang.String geneeicSort) {
		set("GENEEIC_SORT", geneeicSort);
	}

	public java.lang.String getGeneeicSort() {
		return get("GENEEIC_SORT");
	}

	public void setMediumSort(java.lang.String mediumSort) {
		set("MEDIUM_SORT", mediumSort);
	}

	public java.lang.String getMediumSort() {
		return get("MEDIUM_SORT");
	}

	public void setSubclassSort(java.lang.String subclassSort) {
		set("SUBCLASS_SORT", subclassSort);
	}

	public java.lang.String getSubclassSort() {
		return get("SUBCLASS_SORT");
	}

	public void setUptime(Timestamp uptime) {
		set("UPTIME", uptime);
	}

	public String getUptime() {
		Object modifierTime = get("UPTIME");
		if (null == modifierTime)
			return null;
		if (modifierTime instanceof String && null != modifierTime)
			return modifierTime.toString();
		else if (modifierTime instanceof oracle.sql.TIMESTAMP) {
			oracle.sql.TIMESTAMP mt = (TIMESTAMP) modifierTime;
			try {
				return new DateTime(mt.timestampValue()).toString("yyyy-MM-dd HH:mm:ss");
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		return null;
	}

	public void setAppNo(java.lang.String appNo) {
		set("APP_NO", appNo);
	}

	public java.lang.String getAppNo() {
		return get("APP_NO");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public void setSysName(java.lang.String sysName) {
		set("SYS_NAME", sysName);
	}

	public java.lang.String getSysName() {
		return get("SYS_NAME");
	}

	public void setIfPatchBolt(java.lang.String ifPatchBolt) {
		set("IF_PATCH_BOLT", ifPatchBolt);
	}

	public java.lang.String getIfPatchBolt() {
		return get("IF_PATCH_BOLT");
	}

	public void setIfWaste(java.lang.String ifWaste) {
		set("IF_WASTE", ifWaste);
	}

	public java.lang.String getIfWaste() {
		return get("IF_WASTE");
	}

	public void setCreator(java.lang.String creator) {
		set("CREATOR", creator);
	}

	public java.lang.String getCreator() {
		return get("CREATOR");
	}

	public void setCreateJobnum(java.lang.String createJobnum) {
		set("CREATE_JOBNUM", createJobnum);
	}

	public java.lang.String getCreateJobnum() {
		return get("CREATE_JOBNUM");
	}

	public void setCreateTime(Timestamp createTime) {
		set("CREATE_TIME", createTime);
	}

	public String getCreateTime() {
		Object modifierTime = get("CREATE_TIME");
		if (null == modifierTime)
			return null;
		if (modifierTime instanceof String && null != modifierTime)
			return modifierTime.toString();
		else if (modifierTime instanceof oracle.sql.TIMESTAMP) {
			oracle.sql.TIMESTAMP mt = (TIMESTAMP) modifierTime;
			try {
				return new DateTime(mt.timestampValue()).toString("yyyy-MM-dd HH:mm:ss");
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		return null;
	}

	public void setModifier(java.lang.String modifier) {
		set("MODIFIER", modifier);
	}

	public java.lang.String getModifier() {
		return get("MODIFIER");
	}

	public void setModifiedJobnum(java.lang.String modifiedJobnum) {
		set("MODIFIED_JOBNUM", modifiedJobnum);
	}

	public java.lang.String getModifiedJobnum() {
		return get("MODIFIED_JOBNUM");
	}

	public void setModifierTime(Timestamp modifierTime) {
		set("MODIFIER_TIME", modifierTime);
	}

	public String getModifierTime() {
		Object modifierTime = get("MODIFIER_TIME");
		if (null == modifierTime)
			return null;
		if (modifierTime instanceof String && null != modifierTime)
			return modifierTime.toString();
		else if (modifierTime instanceof oracle.sql.TIMESTAMP) {
			oracle.sql.TIMESTAMP mt = (TIMESTAMP) modifierTime;
			try {
				return new DateTime(mt.timestampValue()).toString("yyyy-MM-dd HH:mm:ss");
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		return null;
	}

	public void setDataSources(java.math.BigDecimal dataSources) {
		set("DATA_SOURCES", dataSources);
	}

	public java.math.BigDecimal getDataSources() {
		return get("DATA_SOURCES");
	}

	public void setVersion(Integer v) {
		set("VERSION", v);
	}

	public Integer getVersion() {
		return getInt("VERSION");
	}
}
