package com.yuminsoft.cps.pic.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOldPicture<M extends BaseOldPicture<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setFilepath(java.lang.String filepath) {
		set("FILEPATH", filepath);
	}

	public java.lang.String getFilepath() {
		return get("FILEPATH");
	}

	public void setLoanId(java.math.BigDecimal loanId) {
		set("LOAN_ID", loanId);
	}

	public java.math.BigDecimal getLoanId() {
		return get("LOAN_ID");
	}

	public void setSmallIcon(java.lang.String smallIcon) {
		set("SMALL_ICON", smallIcon);
	}

	public java.lang.String getSmallIcon() {
		return get("SMALL_ICON");
	}

	public void setFileName(java.lang.String fileName) {
		set("FILE_NAME", fileName);
	}

	public java.lang.String getFileName() {
		return get("FILE_NAME");
	}

}
