package com.yuminsoft.cps.pic.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFiletag<M extends BaseFiletag<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setTagName(java.lang.String tagName) {
		set("TAG_NAME", tagName);
	}

	public java.lang.String getTagName() {
		return get("TAG_NAME");
	}

}
