package com.yuminsoft.cps.pic.common.model;

import com.yuminsoft.cps.pic.common.model.base.BaseFiletagPicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FiletagPicture extends BaseFiletagPicture<FiletagPicture> {
	
	public static final  FiletagPicture me = new FiletagPicture().dao();
	
	public static final String seq = "FILETAG_PICTURE_SEQ.nextval";

}
