package com.yuminsoft.cps.pic.common.model;

import com.yuminsoft.cps.pic.common.model.base.BaseFiletag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Filetag extends BaseFiletag<Filetag> {
	public static final Filetag me = new Filetag().dao();
	/**
	   * 序列名称
	   */
	public static final String seq = "FILETAG_SEQ.nextval";
}
