package com.yuminsoft.cps.pic.common.model;

import com.yuminsoft.cps.pic.common.model.base.BaseOldPicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OldPicture extends BaseOldPicture<OldPicture> {

	public static final OldPicture me = new OldPicture().dao();
}
