package com.yuminsoft.cps.pic.common.model;

import com.yuminsoft.cps.pic.common.model.base.BasePaperstype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paperstype extends BasePaperstype<Paperstype> {
	public static final Paperstype me = new Paperstype().dao();
	/**
	 * 序列名称
	 */
	public static final String seq = "PAPERSTYPE_SEQ.nextval";

	/**
	 * 通过编号获取
	 * 
	 * @param itemCode
	 * @return
	 */
	public Paperstype getByItemCode(String itemCode) {
		return this.findFirst("select * from PAPERSTYPE where ITEM_CODE=?", itemCode);
	}
}
