package com.yuminsoft.cps.pic.common.model;

import com.yuminsoft.cps.pic.common.model.base.BasePrivilege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Privilege extends BasePrivilege<Privilege> {
	public static final Privilege me = new Privilege().dao();
	/**
	   * 序列名称						
	   */
	public static final String seq = "PRIVILEGE_SEQ.nextval";
	
	public void setItemValue(java.lang.String itemValue) {
		put("ITEM_VALUE", itemValue);
	}

	public java.lang.String getItemValue() {
		return get("ITEM_VALUE");
	}
	
	public void setItemCode(java.lang.String itemValue) {
		put("ITEM_CODE", itemValue);
	}

	public java.lang.String getItemCode() {
		return get("ITEM_CODE");
	}

	public void setSysName(java.lang.String sysName) {
		put("SYS_NAME", sysName);
	}

	public java.lang.String getSysName() {
		return get("SYS_NAME");
	}
	
}
