package com.yuminsoft.cps.pic.common.model;



import com.yuminsoft.cps.pic.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static Role me = new Role().dao();
	/**
	   * 序列名称						
	   */
	public static final String seq = "Role_SEQ.nextval";
	
}
